### ISSUE TITLE
OnboardingScreen>SiteStatus Component needs a site/store copy update

### ISSUE THREAD

**Issue by circlecube** [newfold-labs/wp-module-ecommerce#110]
This section has 2 leftover references to **store** which are not conditional on the site being a store.

"Preview your store before setting it live to make sure everything is how you want it. Once you're ready, set your store live!"
See: https://github.com/newfold-labs/wp-module-ecommerce/blob/trunk/src/components/SiteStatus.js#L57

This text should be updated to state **site** when not a store as is done in other places (see: https://github.com/newfold-labs/wp-module-ecommerce/blob/trunk/src/components/OnboardingList.js#L73-L75)

In this screenshot for a site, the buttons correctly reference the site, but the text still references a store. Note that there are two references to "store" which should both be conditionally changed to "site".
<img width="650" alt="Screenshot 2023-08-03 at 11 02 28" src="https://github.com/newfold-labs/wp-module-ecommerce/assets/698049/f63d64f3-3f71-4853-b6f3-4e7daa361c37">

Optionally, we could update many of these instances to site, since that applies to both a site and a store, while store would never apply to a site. Having said that, this does look to be the last instance where it needs updating.

**Comment by sumathi3399** [comment]
Fixed by https://github.com/newfold-labs/wp-module-ecommerce/pull/112
