### ISSUE TITLE
Launch action always references site as store

### ISSUE THREAD

**Issue by circlecube** [newfold-labs/wp-module-ecommerce#94]
When coming soon is active the section displays to launch the site. The text refers to the site as a store, which makes sense if the site is a store, but not all sites are stores. Perhaps we can update the verbiage here so it will at least reflect if the site is a store or not.

It could depend on if the site has woo installed or if it has `isEcommerce` capabilities.

<img width="715" alt="Screenshot 2023-06-14 at 13 54 30" src="https://github.com/newfold-labs/wp-module-ecommerce/assets/698049/cd7c8f2e-9dc3-4c4d-978c-d0bf71eebeed">

**Comment by aulisius** [comment]
Fixed with #93
